CREATE DATABASE T_Rental_Vitor

USE T_Rental_Vitor

CREATE TABLE EMPRESA(
idEmpresa TINYINT PRIMARY KEY IDENTITY,
NomeEmpresa VARCHAR(30) UNIQUE,
)
GO

CREATE TABLE MARCA(
idMarca SMALLINT PRIMARY KEY IDENTITY,
NomeMarca VARCHAR(35) UNIQUE,
)
GO

CREATE TABLE MODELO(
idModelo SMALLINT PRIMARY KEY IDENTITY,
NomeModelo VARCHAR(30) UNIQUE,
idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
)
GO

CREATE TABLE PLACA(
idPlaca INT PRIMARY KEY IDENTITY,
NumeroPlaca CHAR(7) UNIQUE,
)
GO

CREATE TABLE VEICULO(
idVeiculo INT PRIMARY KEY IDENTITY,
idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
idEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
idPlaca INT FOREIGN KEY REFERENCES PLACA(idPlaca),
)
GO

CREATE TABLE CLIENTE(
idCliente SMALLINT PRIMARY KEY IDENTITY,
Nome VARCHAR(15),
Sobrenome VARCHAR(15),
CPF CHAR(11) UNIQUE,
)
GO

CREATE TABLE ALUGUEL(
idAluguel INT PRIMARY KEY IDENTITY,
idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
DataRetirada DATETIME,
DataEntrega DATETIME,
)
Go